<a href="https://colab.research.google.com/github/vivianagonzalez203/Bootcamp-Data-Science/blob/main/02_Python/Clase_08_Limpieza_Datos_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Limpieza de datos con Pandas**
## Ventas de una tienda colombiana


**Herramienta:** Pandas  
**Objetivo:** transformar un dataset deliberadamente sucio en un conjunto de datos confiable para análisis.

> **Idea central de la clase:** limpiar datos no significa simplemente borrar filas. Significa **detectar problemas, entenderlos, tomar decisiones y validar que el resultado sea confiable**.

### Ruta de trabajo

1. Conocer el dataset
2. Diagnosticar problemas
3. Tratar valores nulos
4. Detectar y eliminar duplicados
5. Limpiar texto y categorías
6. Corregir tipos de datos
7. Limpiar fechas
8. Detectar valores inválidos
9. Crear variables después de limpiar
10. Validar el resultado final

## Pregunta guía
> **¿Se puede confiar en estos datos?**


**Regla:** antes de modificar el DataFrame, primero se intenta entender el problema.

## 1. Importar Pandas y cargar los datos

Archivo esperado:

`df_ventas.csv`

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving df_ventas.csv to df_ventas.csv

In [ ]:
df = pd.read_csv("df_ventas.csv")

df.head()

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
0,V1180,18/05/2026,Natalia Jiménez,MEDELLÍN,Laptop,TECNOLOGÍA,6,2500000,0,Daviplata,37.0,Luisa
1,V0343,2026/02/08,Gabriela Muñoz,ARMENIA,Mouse,Tecnología,3,45000,0%,Transferencia,56.0,Luisa
2,V0650,27/02/2026,Carlos Vargas,MANIZALES,Audífonos,Tecnología,5,180000,0.15,Transferencia,35.0,Diana
3,V0773,26/03/26,Luisa Fernández,cali,Mouse,TECNOLOGÍA,5,45000,0%,Efectivo,23.0,Diana
4,V0804,21/05/26,Camila Torres,bogotá,Bolígrafo,Papelería,4,3500,0%,Tarjeta,41.0,Carlos

### Preguntas:

- ¿Qué puede estar mal?
- ¿Qué columnas parecen susceptibles a errores?

# 2. Diagnóstico inicial

> **¿Qué se tiene y cómo está almacenado?**

In [ ]:
df.shape

(1275, 12)

### `shape`

Devuelve una tupla:

`(filas, columnas)`

Conocer rápidamente el tamaño del dataset.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         1275 non-null   object
 1   fecha            1267 non-null   object
 2   cliente          1240 non-null   object
 3   ciudad           1249 non-null   object
 4   producto         1275 non-null   object
 5   categoria        1257 non-null   object
 6   cantidad         1275 non-null   int64
 7   precio_unitario  1263 non-null   object
 8   descuento        1255 non-null   object
 9   metodo_pago      1259 non-null   object
 10  edad_cliente     1247 non-null   float64
 11  vendedor         1265 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 119.7+ KB

### `info()`

Permite observar:

- cantidad de registros
- nombres de columnas
- valores no nulos
- tipo de dato de cada columna

In [ ]:
df.describe()

          cantidad  edad_cliente
count  1275.000000   1247.000000
mean      3.385882     45.207698
std       1.804004     20.881328
min      -3.000000     -5.000000
25%       2.000000     30.000000
50%       3.000000     44.000000
75%       5.000000     59.000000
max       6.000000    200.000000

### `describe()`

Resume principalmente las columnas numéricas.

Importante: que una columna aparezca como numérica **no significa automáticamente que sus valores sean correctos**.

## 3. ¿Dónde están los valores faltantes?

In [ ]:
df.isnull().sum()

id_venta            0
fecha               8
cliente            35
ciudad             26
producto            0
categoria          18
cantidad            0
precio_unitario    12
descuento          20
metodo_pago        16
edad_cliente       28
vendedor           10
dtype: int64

### `isnull()`

Identifica valores faltantes.

Al agregar `sum()` cuenta cuántos faltantes existen en cada columna.

# 4. Tratamiento de valores nulos

Hay varias estrategias posibles.

### Opción A — Eliminar filas

```python
df.dropna()
```

### Opción B — Eliminar según una columna específica

```python
df.dropna(subset=["ciudad"])
```

### Opción C — Completar con un valor

```python
df["ciudad"].fillna("Desconocida")
```

### Opción D — Imputar con una medida

Por ejemplo, para una variable numérica:

```python
df["edad_cliente"].fillna(df["edad_cliente"].median())
```

### Decisión de negocio

No existe una función universalmente correcta.

La pregunta no es:

> "¿Qué función uso?"

La pregunta es:

> **"¿Qué debería significar un valor faltante en este contexto?"**

In [ ]:
df[df["ciudad"].isnull()].head(10)

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
6,V0045,2026-05-01,Juliana Morales,NaN,Audífonos,tecnologia,4,180000,0.15,Daviplata,25.0,Andrés
40,V0129,11/07/26,Laura Gómez,NaN,Impresora,TECNOLOGÍA,5,650000,10%,Tarjeta,60.0,Felipe
47,V0583,13/03/2026,Sofía Ramírez,NaN,Impresora,TECNOLOGÍA,-3,650000,0%,Daviplata,25.0,Felipe
163,V1134,2026-01-31,Pedro Ruiz,NaN,Celular,Tecnología,4,1800000,15%,Daviplata,NaN,Diana
202,V1220,28-03-2026,Camila Torres,NaN,Bolígrafo,papeleria,6,3500,5%,Tarjeta,-5.0,María
210,V0523,27/06/2026,Sofía Ramírez,NaN,Cuaderno,Papelería,6,12000,15%,Tarjeta,18.0,Carlos
214,V1170,03/06/2026,Juliana Morales,NaN,Teclado,Tecnología,1,120000,15%,Transferencia,37.0,María
291,V1043,25-06-2026,Luisa Fernández,NaN,Bolígrafo,PAPELERÍA,3,3500,0%,Tarjeta,43.0,Felipe
318,V0629,17-07-2026,Manuela Cárdenas,NaN,Cuaderno,papeleria,5,12000,5%,Efectivo,42.0,Andrés
384,V1033,2026-06-18,Luisa Fernández,NaN,Cuaderno,papeleria,3,12000,0%,Transferencia,34.0,Felipe

In [ ]:
df["ciudad"] = df["ciudad"].fillna("Desconocida")

Para `edad_cliente`, en cambio, podemos utilizar la mediana como ejercicio de imputación.

¿Por qué la mediana y no la media?

Porque suele ser menos sensible a valores extremos.

In [ ]:
mediana_edad = df["edad_cliente"].median()

df["edad_cliente"] = df["edad_cliente"].fillna(mediana_edad)

mediana_edad

44.0

In [ ]:
df["edad_cliente"] = df["edad_cliente"].fillna(mediana_edad)

### Verificación

In [ ]:
df.isnull().sum()

id_venta            0
fecha               8
cliente            35
ciudad              0
producto            0
categoria          18
cantidad            0
precio_unitario    12
descuento          20
metodo_pago        16
edad_cliente        0
vendedor           10
dtype: int64

# 5. Duplicados

> **¿Cuántas filas están duplicadas exactamente?**

In [ ]:
df.duplicated().sum()

np.int64(24)

### Ver las filas duplicadas

In [ ]:
df[df.duplicated()].head(20)

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
53,V1044,13/07/26,Laura Gómez,Bogotá,Celular,Tecnología,4,1800000,10%,Nequi,25.0,María
106,V0514,22/05/26,Ana Pérez,Armenia,Bolígrafo,papeleria,4,3500,15%,Transferencia,62.0,Diana
348,V0681,07/06/26,Juliana Morales,Pereira,Mouse,tecnologia,3,45000,10%,Tarjeta,200.0,Carlos
371,V1051,2026-03-20,Sofía Ramírez,Armenia,Bolígrafo,papeleria,3,3500,5%,Tarjeta,59.0,Andrés
396,V0498,25-07-2026,Pedro Ruiz,Dosquebradas,Maletín,Accesorios,4,190000,0%,Nequi,53.0,Luisa
397,V1171,09-07-2026,Mateo Díaz,Pereira,Mochila,Accesorios,5,140000,10%,Transferencia,69.0,Luisa
448,V0129,11/07/26,Laura Gómez,Desconocida,Impresora,TECNOLOGÍA,5,650000,10%,Tarjeta,60.0,Felipe
458,V1168,08/02/2026,Juan López,Medellín,Agenda,Papelería,2,25000,0.05,Transferencia,62.0,Carlos
485,V0395,2026-02-22,Daniel Moreno,Cali,Mochila,Accesorios,5,140000,0%,Efectivo,40.0,Felipe
491,V0744,18-07-2026,Paula Sánchez,Cali,Silla ergonómica,Oficina,3,720000,0%,Efectivo,62.0,Andrés
534,V0779,09/05/2026,Valentina Rodríguez,Dosquebradas,Audífonos,tecnologia,3,180000,0.1,Daviplata,31.0,Diana
546,V0210,22/04/26,Sofía Ramírez,MANIZALES,Cuaderno,Papelería,2,12000,0.05,Tarjeta,22.0,Diana
691,V0271,01-01-2026,Carlos Vargas,Bogotá,Mochila,accesorios,6,140000,15%,Transferencia,32.0,Luisa
769,V0463,08/07/2026,Valentina Rodríguez,Medellín,Cuaderno,Papelería,3,12000,15%,Nequi,65.0,Luisa
824,V0946,17/03/2026,Gabriela Muñoz,Medellín,Audífonos,Tecnología,6,180000,0.15,Tarjeta,60.0,Felipe
952,V1140,2026-02-28,Ana Pérez,cartago,Celular,Tecnología,4,1800000,0%,NaN,69.0,Felipe
969,V0044,14/03/26,Daniel Moreno,Medellín,Escritorio,Oficina,1,580000,5%,Tarjeta,26.0,Felipe
976,V0943,2026-05-01,Juan López,MEDELLÍN,Laptop,TECNOLOGÍA,2,2500000,0%,Tarjeta,70.0,Carlos
984,V0082,2026-01-28,Luisa Fernández,Bogota,Mochila,accesorios,2,140000,15%,Transferencia,39.0,Andrés
995,V1103,04-02-2026,Gabriela Muñoz,PEREIRA,Escritorio,Oficina,6,$580.000,20%,Tarjeta,48.0,Luisa

### Eliminar duplicados exactos

In [ ]:
df = df.drop_duplicates()

df.shape

# .drop() - Elimina algo

(1251, 12)

## Duplicado técnico vs. duplicado lógico


Dos registros pueden no ser exactamente iguales:

```text
Pereira
pereira
PEREIRA
 Pereira
```

# 6. Limpieza de texto

Los más importantes:

- `.str.strip()` → elimina espacios al inicio y final
- `.str.lower()` → minúsculas
- `.str.upper()` → mayúsculas
- `.str.title()` → Iniciales en mayúscula
- `.str.replace()` → reemplazar texto

In [ ]:
df["ciudad"].value_counts()

ciudad
MANIZALES       69
armenia         69
CARTAGO         65
dosquebradas    62
Dosquebradas    58
Manizales       51
Armenia         50
 Medellín       47
cali            46
cartago         45
manizales       41
medellin        41
 Bogotá         40
 Cali           39
MEDELLÍN        37
Cartago         37
Medellín        37
BOGOTA          36
CALI            35
pereira         34
ARMENIA         34
DOSQUEBRADAS    32
PEREIRA         31
Bogotá          30
Cali            28
Bogota          28
bogotá          27
Pereira         26
 Pereira        26
Desconocida     25
Pereira         25
Name: count, dtype: int64

In [ ]:
df["ciudad"] = (
    df["ciudad"]
    .str.strip()
    .str.lower()
    .str.title()
)

df["ciudad"].value_counts()

ciudad
Manizales       161
Armenia         153
Dosquebradas    152
Cali            148
Cartago         147
Pereira         142
Medellín        121
Bogotá           97
Bogota           64
Medellin         41
Desconocida      25
Name: count, dtype: int64

In [ ]:
df["ciudad"] = (
    df["ciudad"]
    .str.replace("Medellin", "Medellín", regex=False)
    .str.replace("Bogota", "Bogotá", regex=False)
)

In [ ]:
df["ciudad"].value_counts()

ciudad
Medellín        162
Manizales       161
Bogotá          161
Armenia         153
Dosquebradas    152
Cali            148
Cartago         147
Pereira         142
Name: count, dtype: int64

### Se repite el proceso con `categoria`

In [ ]:
df["categoria"].value_counts()

categoria
Tecnología      140
tecnologia      139
 Tecnologia     133
Tecnología      127
TECNOLOGÍA      122
Papelería        63
papeleria        62
 Papelería       61
PAPELERÍA        58
Oficina          51
accesorios       45
Accesorios       45
ACCESORIOS       42
oficina          42
 Oficina         41
OFICINA          38
 Accesorios      24
Name: count, dtype: int64

In [ ]:
df["categoria"] = (
    df["categoria"]
    .str.strip()
    .str.lower()
    .str.title()
)

df["categoria"].value_counts()

categoria
Tecnología    389
Tecnologia    272
Papelería     182
Oficina       172
Accesorios    156
Papeleria      62
Name: count, dtype: int64

In [ ]:
df["categoria"] = (
    df["categoria"]
    .str.replace("Tecnología", "Tecnologia", regex=False)
)

In [ ]:
df["categoria"].value_counts()

categoria
Tecnologia    661
Papelería     182
Oficina       172
Accesorios    156
Papeleria      62
Name: count, dtype: int64

### También podemos limpiar nombres de clientes

In [ ]:
df["cliente"] = df["cliente"].str.strip()

# 7. Tipos de datos

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1251 entries, 0 to 1274
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         1251 non-null   object
 1   fecha            1243 non-null   object
 2   cliente          1216 non-null   object
 3   ciudad           1251 non-null   object
 4   producto         1251 non-null   object
 5   categoria        1233 non-null   object
 6   cantidad         1251 non-null   int64
 7   precio_unitario  1239 non-null   object
 8   descuento        1231 non-null   object
 9   metodo_pago      1236 non-null   object
 10  edad_cliente     1251 non-null   float64
 11  vendedor         1241 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 127.1+ KB

### Problema

`precio_unitario` puede estar almacenado como texto porque contiene valores como:

```text
2500000
$850.000
```

In [ ]:
df["precio_unitario"].head(10)

0       2500000
1         45000
2        180000
3         45000
4          3500
5    $1.100.000
6        180000
7        140000
8         25000
9        580000
Name: precio_unitario, dtype: object

## Limpiar el precio

Eliminar el símbolo `$` y los separadores de miles.

In [ ]:
df["precio_unitario"] = (
    df["precio_unitario"]
    .astype("string") # .astype () - convierte columna a texto
    .str.replace("$", "", regex=False)
    .str.replace(".", "", regex=False) # regex=False = busca exactamente ese texto, sin interpretarlo como una expresión regular
)

In [ ]:
df["precio_unitario"].head(10)

0    2500000
1      45000
2     180000
3      45000
4       3500
5    1100000
6     180000
7     140000
8      25000
9     580000
Name: precio_unitario, dtype: string

### Convertir a número

`pd.to_numeric()` intenta convertir los valores a un tipo numérico.

Con `errors="coerce"` los valores que no puedan convertirse pasan a ser `NaN`.

In [ ]:
df["precio_unitario"] = pd.to_numeric(
    df["precio_unitario"],
    errors="coerce"
)

df["precio_unitario"].dtype

Int64Dtype()

# 8. Limpiar descuentos %

Los descuentos aparecen con formatos como:

```text
10%
5%
0%
0.1
```

In [ ]:
df["descuento"].head(10)

0       0
1      0%
2    0.15
3      0%
4      0%
5      5%
6    0.15
7     10%
8     15%
9      5%
Name: descuento, dtype: object

In [ ]:
df["descuento"] = (
    df["descuento"]
    .astype("string")
    .str.replace("%", "", regex=False)
)

df["descuento"] = pd.to_numeric(
    df["descuento"],
    errors="coerce"
)

Ahora tenemos los porcentajes como números.

Para trabajar con el descuento en cálculos, se puede convertir a proporción:

`10` → `0.10`

`5` → `0.05`

In [ ]:
df["descuento"] = df["descuento"] / 100

In [ ]:
df["descuento"].head(10)

0       0.0
1       0.0
2    0.0015
3       0.0
4       0.0
5      0.05
6    0.0015
7       0.1
8      0.15
9      0.05
Name: descuento, dtype: Float64

# 9. Fechas

In [ ]:
df["fecha"].head(10)

0    18/05/2026
1    2026/02/08
2    27/02/2026
3      26/03/26
4      21/05/26
5    01-04-2026
6    2026-05-01
7    45/05/2026
8      20/07/26
9      14/03/26
Name: fecha, dtype: object

Se encuentran formatos diferentes:

- `2026-01-05`
- `05/01/2026`
- `2026/01/07`
- `08-01-2026`

In [ ]:
df["fecha"] = pd.to_datetime(
    df["fecha"],
    errors="coerce",
    format="mixed",
    dayfirst=True
)

### ¿Qué significa `NaT`?

`NaT` significa **Not a Time**.

Es el equivalente a un valor faltante para fechas y tiempos.

In [ ]:
df[df["fecha"].isnull()]

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
7,V0232,NaT,Sofía Ramírez,Armenia,Mochila,Accesorios,0,140000,0.1,Tarjeta,66.0,Andrés
11,V0064,NaT,Luisa Fernández,Manizales,Escritorio,Oficina,6,580000,0.05,Nequi,26.0,Andrés
216,V1088,NaT,Laura Gómez,Cartago,Bolígrafo,Papelería,2,3500,0.1,Daviplata,67.0,Carlos
241,V0920,NaT,Natalia Jiménez,Pereira,Mochila,Accesorios,4,140000,0.15,Efectivo,46.0,Diana
244,V0332,NaT,Gabriela Muñoz,Bogotá,Laptop,Tecnologia,4,2500000,0.2,Nequi,38.0,Diana
347,V1167,NaT,Camila Torres,Pereira,Mochila,Accesorios,0,140000,0.0,Transferencia,63.0,Diana
361,V0040,NaT,Nicolás Quintero,Dosquebradas,Mochila,Accesorios,5,140000,0.1,Nequi,46.0,Andrés
363,V0243,NaT,Daniel Moreno,Armenia,Maletín,Accesorios,2,190000,<NA>,Efectivo,26.0,María
387,V0967,NaT,Mateo Díaz,Cali,Agenda,Papelería,6,25000,0.002,Efectivo,54.0,Felipe
446,V1030,NaT,Diego Restrepo,Armenia,Cuaderno,Papelería,4,12000,0.0005,Transferencia,33.0,María
461,V0107,NaT,Sebastián Rojas,Pereira,Mouse,Tecnologia,3,45000,0.0,Efectivo,67.0,Andrés
478,V0885,NaT,Mateo Díaz,Manizales,Monitor,Tecnologia,3,850000,0.05,Tarjeta,43.0,Felipe
557,V0072,NaT,Manuela Cárdenas,Armenia,Mochila,Accesorios,4,140000,0.0,Nequi,56.0,Felipe
726,V0849,NaT,Sebastián Rojas,Pereira,Silla ergonómica,Oficina,4,720000,0.1,Transferencia,59.0,Felipe
781,V0418,NaT,Luisa Fernández,Manizales,Bolígrafo,Papelería,5,3500,0.2,Tarjeta,48.0,Carlos
992,V0983,NaT,Laura Gómez,Medellín,Agenda,Papelería,2,25000,0.15,Nequi,44.0,María

In [ ]:
df.shape

(1251, 12)

# 10. Valores inválidos

Un dato puede tener el tipo correcto y aun así estar mal.

Ejemplo:

```text
edad_cliente = 150
cantidad = -3
```

## Revisión de las edades

In [ ]:
df[df["edad_cliente"] < 18][["id_venta", "cliente", "edad_cliente"]].head(20)

     id_venta              cliente  edad_cliente
87      V1136           Mateo Díaz           0.0
202     V1220        Camila Torres          -5.0
337     V0275         Felipe Arias          -5.0
482     V1076      Luisa Fernández          -5.0
628     V0526  Valentina Rodríguez          -5.0
673     V0070      Andrés Martínez           0.0
725     V0949          Laura Gómez           0.0
935     V0354       Diego Restrepo           0.0
1057    V1071         Felipe Arias           0.0
1088    V0147          Laura Gómez           0.0
1264    V1124            Ana Pérez           0.0
1273    V0861      Natalia Jiménez           0.0

Se consideraran válidas las edades entre 18 y 100 años.

In [ ]:
df[
    (df["edad_cliente"] < 18) |
    (df["edad_cliente"] > 100)
][["id_venta", "cliente", "edad_cliente"]].head(20)

     id_venta              cliente  edad_cliente
79      V0860          Laura Gómez         150.0
87      V1136           Mateo Díaz           0.0
202     V1220        Camila Torres          -5.0
228     V0681      Juliana Morales         200.0
249     V0995       Diego Restrepo         150.0
260     V1079      Luisa Fernández         200.0
337     V0275         Felipe Arias          -5.0
462     V0950        Carlos Vargas         150.0
482     V1076      Luisa Fernández          -5.0
536     V0335  Valentina Rodríguez         150.0
617     V0954           Mateo Díaz         150.0
628     V0526  Valentina Rodríguez          -5.0
673     V0070      Andrés Martínez           0.0
694     V0799        Camila Torres         200.0
725     V0949          Laura Gómez           0.0
935     V0354       Diego Restrepo           0.0
1057    V1071         Felipe Arias           0.0
1060    V1129      Natalia Jiménez         200.0
1088    V0147          Laura Gómez           0.0
1103    V1158            Ana Pérez         200.0

En lugar de borrar inmediatamente las filas, se convertiran esos valores inválidos en faltantes.

In [ ]:
condicion_edad = (
    (df["edad_cliente"] < 18) |
    (df["edad_cliente"] > 100)
)

df.loc[condicion_edad, "edad_cliente"] = pd.NA

## Revisamos las cantidades

Una venta no debería tener una cantidad menor o igual a cero.

In [ ]:
df[df["cantidad"] <= 0][
    ["id_venta", "producto", "cantidad"]
]

     id_venta    producto  cantidad
7       V0232     Mochila         0
47      V0583   Impresora        -3
52      V0307  Escritorio         0
115     V0334      Laptop        -1
136     V1132      Tablet         0
209     V0478     Teclado        -3
251     V1106      Tablet        -1
347     V1167     Mochila         0
354     V0543   Audífonos        -1
366     V0311  Escritorio         0
395     V0712  Escritorio        -3
476     V0561      Agenda        -1
480     V0631   Audífonos         0
558     V0095       Mouse        -3
612     V0786     Celular         0
620     V0794     Celular        -1
650     V0505     Monitor        -3
690     V0194   Audífonos        -1
693     V0170       Mouse        -3
735     V1250  Escritorio        -3
762     V0689    Cuaderno         0
901     V0047  Escritorio        -1
928     V0698       Mouse         0
1086    V0489     Monitor        -1
1183    V0593     Maletín         0
1217    V1026     Maletín         0
1268    V0467      Agenda        -1
1274    V1127    Cuaderno        -3

Se consideraran estos registros como inválidos y se eliminaran.

**Importante:** no siempre se eliminan datos inválidos. Esta es una decisión de negocio.

In [ ]:
df = df[df["cantidad"] > 0].copy()

# 11. Revisión de precios

Precios menores o iguales a cero.

In [ ]:
df[df["precio_unitario"] <= 0][
    ["id_venta", "producto", "precio_unitario"]
]

     id_venta          producto  precio_unitario
25      V0782            Agenda           -50000
94      V0963         Audífonos           -50000
130     V0356            Laptop                0
187     V0494         Audífonos           -50000
204     V0652          Cuaderno           -50000
218     V0011           Monitor                0
434     V0312         Audífonos                0
615     V0008         Audífonos                0
705     V0235             Mouse                0
805     V0545            Laptop                0
847     V0902           Monitor                0
914     V0444         Bolígrafo                0
1017    V0172             Mouse           -50000
1073    V0881  Silla ergonómica                0
1096    V0144          Cuaderno                0
1116    V0113         Impresora           -50000

Revisar valores extremadamente altos.

In [ ]:
df["precio_unitario"].describe()

count             1211.0
mean      1662583.391412
std      10272273.205826
min             -50000.0
25%              45000.0
50%             190000.0
75%             850000.0
max           99999999.0
Name: precio_unitario, dtype: Float64

In [ ]:
df[df["precio_unitario"] >= 3000000][
    ["id_venta", "producto", "precio_unitario"]
]

     id_venta    producto  precio_unitario
15      V0077   Bolígrafo         99999999
35      V0024     Celular         99999999
43      V0669     Maletín         99999999
143     V0528     Teclado         99999999
167     V0298      Laptop         99999999
279     V0926   Impresora         99999999
436     V0915      Tablet         99999999
704     V0658   Impresora         99999999
750     V0279     Monitor         99999999
784     V0944  Escritorio         99999999
876     V1082   Audífonos         99999999
996     V0191       Mouse         99999999
1158    V1169      Tablet         99999999

In [ ]:
df[df["precio_unitario"] >= 3000000][
    ["id_venta", "producto", "precio_unitario"]
]

     id_venta    producto  precio_unitario
15      V0077   Bolígrafo         99999999
35      V0024     Celular         99999999
43      V0669     Maletín         99999999
143     V0528     Teclado         99999999
167     V0298      Laptop         99999999
279     V0926   Impresora         99999999
436     V0915      Tablet         99999999
704     V0658   Impresora         99999999
750     V0279     Monitor         99999999
784     V0944  Escritorio         99999999
876     V1082   Audífonos         99999999
996     V0191       Mouse         99999999
1158    V1169      Tablet         99999999

In [ ]:
df = df[df["precio_unitario"] <= 3000000].copy()

In [ ]:
df.shape

(1198, 12)

# 12. Revisamos los métodos de pago

Las categorías también pueden contener inconsistencias.

In [ ]:
df["metodo_pago"].value_counts()

metodo_pago
Efectivo          248
Nequi             247
Tarjeta           238
Transferencia     225
Daviplata         216
tarjeta             6
Transferencia       3
 tarjeta            1
Name: count, dtype: int64

In [ ]:
df["metodo_pago"] = (
    df["metodo_pago"]
    .str.strip()
    .str.lower()
    .str.title()
)

df["metodo_pago"].value_counts()

metodo_pago
Efectivo         248
Nequi            247
Tarjeta          245
Transferencia    228
Daviplata        216
Name: count, dtype: int64

In [ ]:
df.head()

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor
0,V1180,2026-05-18,Natalia Jiménez,Medellín,Laptop,Tecnologia,6,2500000,0.0,Daviplata,37.0,Luisa
1,V0343,2026-02-08,Gabriela Muñoz,Armenia,Mouse,Tecnologia,3,45000,0.0,Transferencia,56.0,Luisa
2,V0650,2026-02-27,Carlos Vargas,Manizales,Audífonos,Tecnologia,5,180000,0.0015,Transferencia,35.0,Diana
3,V0773,2026-03-26,Luisa Fernández,Cali,Mouse,Tecnologia,5,45000,0.0,Efectivo,23.0,Diana
4,V0804,2026-05-21,Camila Torres,Bogotá,Bolígrafo,Papelería,4,3500,0.0,Tarjeta,41.0,Carlos

# 13. Crear variables DESPUÉS de limpiar


**Subtotal = cantidad × precio unitario**

In [ ]:
df["subtotal"] = (
    df["cantidad"] *
    df["precio_unitario"]
)

Calcular el valor del descuento.

In [ ]:
df["valor_descuento"] = (
    df["subtotal"] *
    df["descuento"]
)

Calculo del total.

In [ ]:
df["total_venta"] = (
    df["subtotal"] -
    df["valor_descuento"]
)

In [ ]:
df.head()

,id_venta,fecha,cliente,ciudad,producto,categoria,cantidad,precio_unitario,descuento,metodo_pago,edad_cliente,vendedor,subtotal,valor_descuento
0,V1180,2026-05-18,Natalia Jiménez,Medellín,Laptop,Tecnologia,6,2500000,0.0,Daviplata,37.0,Luisa,15000000,0.0
1,V0343,2026-02-08,Gabriela Muñoz,Armenia,Mouse,Tecnologia,3,45000,0.0,Transferencia,56.0,Luisa,135000,0.0
2,V0650,2026-02-27,Carlos Vargas,Manizales,Audífonos,Tecnologia,5,180000,0.0015,Transferencia,35.0,Diana,900000,1350.0
3,V0773,2026-03-26,Luisa Fernández,Cali,Mouse,Tecnologia,5,45000,0.0,Efectivo,23.0,Diana,225000,0.0
4,V0804,2026-05-21,Camila Torres,Bogotá,Bolígrafo,Papelería,4,3500,0.0,Tarjeta,41.0,Carlos,14000,0.0

# 14. Auditoría final


> **¿Cómo sabemos que nuestro dataset quedó limpio?**

In [ ]:
df.shape

(1198, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1198 entries, 0 to 1273
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         1198 non-null   object
 1   fecha            1184 non-null   datetime64[ns]
 2   cliente          1165 non-null   object
 3   ciudad           1198 non-null   object
 4   producto         1198 non-null   object
 5   categoria        1180 non-null   object
 6   cantidad         1198 non-null   int64
 7   precio_unitario  1198 non-null   Int64
 8   descuento        1179 non-null   Float64
 9   metodo_pago      1184 non-null   object
 10  edad_cliente     1175 non-null   float64
 11  vendedor         1189 non-null   object
 12  subtotal         1198 non-null   Int64
 13  valor_descuento  1179 non-null   Float64
dtypes: Float64(2), Int64(2), datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 145.1+ KB

## Revisamos las reglas de negocio

In [ ]:
print("Edades inválidas:", (
    (df["edad_cliente"] < 18) |
    (df["edad_cliente"] > 100)
).sum())

print("Cantidades inválidas:", (df["cantidad"] <= 0).sum())

Edades inválidas: 0
Cantidades inválidas: 0